name = "SimpleConstants"
uuid = "6ca440b6-64d6-4b6c-88af-e5d091cb43b1"
authors = ["Wonseok Shin <wsshin97@gmail.com> and contributors"]
version = "0.1.3"

[compat]
julia = "^1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
